#!/usr/bin/env bash
#configures an Ubuntu server with the below requirements.
#Requirements:
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

cp /etc/hosts /etc/hosts.bak

sed -i '/127.0.0.1\s\+localhost/ s/127.0.0.1/127.0.0.2/' /etc/hosts

if ! grep -q "8.8.8.8 facebook.com" /etc/hosts; then
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi